import type { RoleProfile } from './role-archetypes.js';

export const ARCHETYPE_SEEDS: RoleProfile[] = [
  {
    function: 'operations',
    industry: 'general',
    scope: 'business-unit',
    success_definition: 'The operation runs better than when this person arrived. Costs are lower, throughput is higher, and the system works when they are not in the room.',
    proof_point_priorities: [
      'multi-site scale with headcount and revenue',
      'cost reduction with specific dollar amounts',
      'systems built that outlasted tenure',
      'crisis management — what did not break',
    ],
    narrative_frame: 'Position as architect of operating systems, not manager of operations. Lead with scale and what was built, not what was managed day to day.',
    cultural_signals: ['continuous improvement', 'Lean', 'Six Sigma', 'operational excellence', 'cross-functional', 'P&L'],
  },
  {
    function: 'finance',
    industry: 'general',
    scope: 'department',
    success_definition: 'Leadership makes better capital decisions because of this person. The financial function is a strategic partner, not a scorekeeper.',
    proof_point_priorities: [
      'capital events — raised debt, managed acquisition, led audit',
      'forecast accuracy and what decisions it enabled',
      'systems built — ERP, FP&A overhaul',
      'times said no and was right',
    ],
    narrative_frame: 'Position as strategic partner who gives leadership the financial clarity to make confident decisions. Not a scorekeeper. Not a compliance function. A decision-enabler.',
    cultural_signals: ['FP&A', 'GAAP', 'audit', 'capital structure', 'M&A', 'ERP', 'strategic planning', 'board reporting'],
  },
  {
    function: 'people',
    industry: 'general',
    scope: 'enterprise',
    success_definition: 'The organization performs better because of how this person designed and led the human systems. Culture survives major transitions.',
    proof_point_priorities: [
      'org transformations with scale',
      'retention and engagement outcomes with numbers',
      'talent pipelines built',
      'culture work connected to business results',
    ],
    narrative_frame: 'Position as architect of human systems, not HR administrator. Every proof point must connect to a business outcome — revenue, retention cost, productivity, or scale.',
    cultural_signals: ['talent strategy', 'organizational design', 'culture transformation', 'HRIS', 'workforce planning', 'succession', 'change management'],
  },
  {
    function: 'sales',
    industry: 'general',
    scope: 'business-unit',
    success_definition: 'Revenue grew. The team performed. The market expanded. This person built a revenue engine, not just a sales team.',
    proof_point_priorities: [
      'revenue numbers in dollars not percentages',
      'quota attainment — actual numbers',
      'team building and development outcomes',
      'named accounts or markets opened',
      'turnaround stories',
    ],
    narrative_frame: 'Position as architect of revenue systems. Lead with what the team produced, not personal sales performance. Show the methodology, not just the results.',
    cultural_signals: ['quota', 'revenue growth', 'territory', 'pipeline', 'enterprise sales', 'channel', 'CRM', 'business development'],
  },
  {
    function: 'supply-chain',
    industry: 'general',
    scope: 'enterprise',
    success_definition: 'The supply chain performed when everything else broke. Cost is lower. Reliability is higher. The network is more resilient than when this person arrived.',
    proof_point_priorities: [
      'cost reduction with specific categories and amounts',
      'resilience stories — COVID, disruptions, supplier failures',
      'network design or redesign',
      'technology implementations — WMS, TMS, S&OP',
    ],
    narrative_frame: 'Position as resilience architect. Post-2020 supply chain executives are strategic assets. Lead with what held when the environment was worst.',
    cultural_signals: ['procurement', 'logistics', 'distribution', 'inventory', 'vendor management', 'S&OP', 'global sourcing', '3PL'],
  },
  {
    function: 'general-management',
    industry: 'general',
    scope: 'business-unit',
    success_definition: 'The business unit grew, turned around, or was built from scratch under full accountability. P&L ownership, people, strategy — all of it.',
    proof_point_priorities: [
      'P&L size and trajectory under ownership',
      'growth or turnaround story with specifics',
      'team built and what those people went on to do',
      'strategic decisions that changed the unit direction',
    ],
    narrative_frame: 'Position as an operator with strategic range. They have run a business end to end. Lead with P&L accountability and the trajectory they drove.',
    cultural_signals: ['general management', 'P&L', 'business unit', 'turnaround', 'growth', 'full accountability', 'cross-functional'],
  },
  {
    function: 'program-delivery',
    industry: 'general',
    scope: 'department',
    success_definition: 'Complex things got done that would not have without this person. The organization executes better because of the systems they put in place.',
    proof_point_priorities: [
      'scale of programs — budget, teams, duration, complexity',
      'delivery outcomes with specifics',
      'PMO built or transformed',
      'stakeholder environments managed',
    ],
    narrative_frame: 'Position as execution architect. Not a coordinator — a leader who brings order to complex systems. Connect every program to its strategic impact.',
    cultural_signals: ['program management', 'PMO', 'delivery', 'stakeholder management', 'governance', 'portfolio', 'change management', 'PMP'],
  },
  {
    function: 'engineering',
    industry: 'manufacturing',
    scope: 'department',
    success_definition: 'The technical function performed and developed the next generation of technical leaders. Technical decisions drove measurable business outcomes.',
    proof_point_priorities: [
      'technical outcomes tied to business results',
      'team development — engineers grown into leaders',
      'capital projects — designed, built, commissioned',
      'technical standards or IP created',
    ],
    narrative_frame: 'Position as technical leader, not technical expert. Lead with business impact of technical decisions, not technical depth. Show the leadership scope, not just the engineering work.',
    cultural_signals: ['engineering', 'quality', 'R&D', 'technical operations', 'capital projects', 'reliability', 'manufacturing engineering', 'ISO', 'regulatory'],
  },
];
