import type { FinalResume } from '@/types/resume';
import type { CompletionData } from '@/types/panels';

export function buildPositioningSummaryText(
  resume: FinalResume | null,
  panelData: CompletionData | null,
): string {
  const lines: string[] = [];

  lines.push('=== Positioning Summary ===');
  lines.push('');

  if (resume?.contact_info?.name) {
    lines.push(`Candidate: ${resume.contact_info.name}`);
  }
  if (resume?.company_name) {
    lines.push(`Target Company: ${resume.company_name}`);
  }
  lines.push('');

  if (panelData?.ats_score != null) {
    lines.push(`ATS Score: ${panelData.ats_score}%`);
  }
  if (panelData?.requirements_addressed != null) {
    lines.push(`Requirements Addressed: ${panelData.requirements_addressed}`);
  }
  if (panelData?.sections_rewritten != null) {
    lines.push(`Sections Written: ${panelData.sections_rewritten}`);
  }
  lines.push('');

  if (resume?.summary) {
    lines.push('--- Summary ---');
    lines.push(typeof resume.summary === 'string' ? resume.summary : String(resume.summary));
    lines.push('');
  }

  lines.push(`Generated: ${new Date().toLocaleDateString()}`);
  lines.push('Generated by Resume Agent');

  return lines.join('\n');
}
