-- discovery_sessions — Persistent store for the "Moment of Recognition" discovery flow.
--
-- Replaces the prior in-memory Map<string, DiscoverySessionState> in
-- server/src/routes/discovery.ts. Each row holds the full session state
-- as JSONB so the discovery conversation can survive server restarts and
-- horizontal scaling.
--
-- Lifecycle:
--   status='active'   — Session in progress; excavation conversation may continue
--   status='complete' — /complete called successfully; CareerIQ profile was saved
--   status='expired'  — Unused; reserved for future server-side TTL enforcement
--
-- One row per (session_id). The session_id is user-supplied or generated by the
-- server as `discovery-<uuid>` during /analyze.
--
-- Rollback:
--   DROP TABLE IF EXISTS discovery_sessions;

CREATE TABLE IF NOT EXISTS discovery_sessions (
  id              text        PRIMARY KEY,
  user_id         uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  session_state   jsonb       NOT NULL DEFAULT '{}',
  status          text        NOT NULL DEFAULT 'active'
                              CHECK (status IN ('active', 'complete', 'expired')),
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE discovery_sessions ENABLE ROW LEVEL SECURITY;

-- Users can only read and write their own rows.
CREATE POLICY "users_own_discovery_sessions"
  ON discovery_sessions
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Primary lookup: active sessions for a given user (used by GET queries, session listing).
CREATE INDEX IF NOT EXISTS idx_discovery_sessions_user
  ON discovery_sessions (user_id, status)
  WHERE status = 'active';

COMMENT ON TABLE discovery_sessions IS
  'Persistent session state for the Moment of Recognition discovery flow. Replaces in-memory Map.';
COMMENT ON COLUMN discovery_sessions.id IS
  'Client-supplied or server-generated session identifier (e.g. discovery-<uuid>). Max 128 chars, alphanumeric + dash/underscore.';
COMMENT ON COLUMN discovery_sessions.session_state IS
  'Full DiscoverySessionState serialized as JSONB: candidate, job_intelligence, benchmark, discovery, conversation_history, excavation_answers, remaining_questions.';
COMMENT ON COLUMN discovery_sessions.status IS
  'active = conversation in progress; complete = CareerIQ profile saved; expired = TTL eviction (reserved).';

-- L-2: Keep updated_at current on every row update (requires moddatetime extension).
CREATE TRIGGER set_discovery_sessions_updated_at
  BEFORE UPDATE ON discovery_sessions
  FOR EACH ROW EXECUTE FUNCTION moddatetime(updated_at);
