-- Add carousel slide data column to content_posts
-- Stores structured multi-slide carousel data generated by the generate_carousel tool
ALTER TABLE content_posts
  ADD COLUMN IF NOT EXISTS carousel_slides JSONB DEFAULT NULL;

COMMENT ON COLUMN content_posts.carousel_slides IS 'Structured carousel slide data for document posts (cover + content + CTA slides)';
