/**
 * Seed Referral Bonus Programs
 *
 * Populates the referral_bonus_programs table with known companies that pay
 * employee referral bonuses. Uses a lookup-or-create pattern against
 * company_directory so it is fully idempotent.
 *
 * Confidence levels:
 *   high   — specific dollar amounts from verifiable public sources
 *   medium — reported on levels.fyi, Glassdoor, or similar crowdsourced sources
 *   low    — "Variable" or unverified company hearsay
 */

import { supabaseAdmin } from '../supabase.js';
import logger from '../logger.js';

// ─── Company data ──────────────────────────────────────────────────────────────

interface ReferralSeedEntry {
  name: string;
  variants?: string[];
  industry?: string;
  domain?: string;
  bonus_amount: string;
  bonus_entry?: string;
  bonus_mid?: string;
  bonus_senior?: string;
  bonus_executive?: string;
  payout_structure?: string;
  diversity_multiplier?: string;
  special_programs?: Record<string, unknown>;
  confidence?: 'high' | 'medium' | 'low';
  data_source?: string;
  notes?: string;
  program_url?: string;
}

const REFERRAL_COMPANIES: ReferralSeedEntry[] = [
  // ─── FAANG + Mega-cap Tech ───────────────────────────────────────────────────

  {
    name: 'Meta',
    variants: ['Facebook', 'Meta Platforms'],
    industry: 'Technology',
    domain: 'meta.com',
    bonus_amount: '$5,000-$10,000',
    bonus_entry: '$1,000-$3,000',
    bonus_senior: '$5,000-$10,000',
    notes: '75 referrals/year limit',
    confidence: 'high',
    data_source: 'levels.fyi',
  },
  {
    name: 'Amazon',
    variants: ['Amazon.com', 'AWS'],
    industry: 'Technology',
    domain: 'amazon.com',
    bonus_amount: '$1,500-$7,000',
    bonus_mid: '$5,000',
    notes: 'L7 and below; varies by org and location',
    confidence: 'high',
    data_source: 'levels.fyi',
  },
  {
    name: 'Google',
    variants: ['Alphabet', 'Google LLC'],
    industry: 'Technology',
    domain: 'google.com',
    bonus_amount: '$2,000+',
    notes: 'Varies by role and level',
    confidence: 'high',
    data_source: 'levels.fyi',
  },
  {
    name: 'Apple',
    variants: ['Apple Inc.'],
    industry: 'Technology',
    domain: 'apple.com',
    bonus_amount: '$1,000-$5,000+',
    notes: 'Varies significantly by role and team',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Microsoft',
    variants: ['Microsoft Corporation', 'MSFT'],
    industry: 'Technology',
    domain: 'microsoft.com',
    bonus_amount: '$2,000-$5,000',
    confidence: 'high',
    data_source: 'levels.fyi',
  },
  {
    name: 'Netflix',
    variants: ['Netflix Inc.'],
    industry: 'Technology',
    domain: 'netflix.com',
    bonus_amount: 'Up to $10,000',
    confidence: 'high',
    data_source: 'levels.fyi',
  },

  // ─── Major Tech ─────────────────────────────────────────────────────────────

  {
    name: 'Reddit',
    industry: 'Technology',
    domain: 'reddit.com',
    bonus_amount: '$5,000-$10,000',
    confidence: 'high',
    data_source: 'levels.fyi',
  },
  {
    name: 'Salesforce',
    variants: ['Salesforce.com'],
    industry: 'Technology',
    domain: 'salesforce.com',
    bonus_amount: '$2,000-$10,000',
    notes: 'Paid $7M+ total in referral bonuses',
    confidence: 'high',
    data_source: 'company announcement',
  },
  {
    name: 'Oracle',
    variants: ['Oracle Corporation'],
    industry: 'Technology',
    domain: 'oracle.com',
    bonus_amount: '$1,000-$4,000',
    confidence: 'high',
    data_source: 'levels.fyi',
  },
  {
    name: 'IBM',
    variants: ['International Business Machines'],
    industry: 'Technology',
    domain: 'ibm.com',
    bonus_amount: '$2,000-$5,000',
    payout_structure: '$850 at 30 days, $5,000 at 90 days',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'Adobe',
    variants: ['Adobe Inc.', 'Adobe Systems'],
    industry: 'Technology',
    domain: 'adobe.com',
    bonus_amount: 'Variable',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Nvidia',
    variants: ['NVIDIA Corporation'],
    industry: 'Technology',
    domain: 'nvidia.com',
    bonus_amount: '$3,000-$6,000',
    bonus_entry: '$3,000-$5,000',
    bonus_senior: '$4,000-$6,000',
    confidence: 'high',
    data_source: 'levels.fyi',
  },
  {
    name: 'Qualcomm',
    variants: ['QUALCOMM Incorporated'],
    industry: 'Technology',
    domain: 'qualcomm.com',
    bonus_amount: '$3,000-$8,000',
    bonus_entry: '$3,000-$5,000',
    bonus_senior: '$5,000-$8,000',
    confidence: 'high',
    data_source: 'levels.fyi',
  },
  {
    name: 'Intel',
    variants: ['Intel Corporation'],
    industry: 'Technology',
    domain: 'intel.com',
    bonus_amount: '$2,000-$4,000',
    diversity_multiplier: '2x for women, minorities, and veterans',
    confidence: 'high',
    data_source: 'levels.fyi',
  },
  {
    name: 'AMD',
    variants: ['Advanced Micro Devices'],
    industry: 'Technology',
    domain: 'amd.com',
    bonus_amount: '$2,000-$5,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Uber',
    industry: 'Technology',
    domain: 'uber.com',
    bonus_amount: '$2,500-$10,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Lyft',
    industry: 'Technology',
    domain: 'lyft.com',
    bonus_amount: '$2,000-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Airbnb',
    industry: 'Technology',
    domain: 'airbnb.com',
    bonus_amount: '$3,000-$10,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Stripe',
    industry: 'Technology',
    domain: 'stripe.com',
    bonus_amount: '$5,000-$15,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Block',
    variants: ['Square', 'Square Inc.'],
    industry: 'Technology',
    domain: 'block.xyz',
    bonus_amount: '$2,000-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Coinbase',
    industry: 'Technology',
    domain: 'coinbase.com',
    bonus_amount: '$5,000-$15,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Robinhood',
    industry: 'Technology',
    domain: 'robinhood.com',
    bonus_amount: '$3,000-$10,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Snap',
    variants: ['Snapchat', 'Snap Inc.'],
    industry: 'Technology',
    domain: 'snap.com',
    bonus_amount: '$2,500-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'X',
    variants: ['Twitter', 'X Corp'],
    industry: 'Technology',
    domain: 'x.com',
    bonus_amount: '$2,000-$7,500',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Pinterest',
    industry: 'Technology',
    domain: 'pinterest.com',
    bonus_amount: '$2,000-$7,500',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'LinkedIn',
    industry: 'Technology',
    domain: 'linkedin.com',
    bonus_amount: '$2,500-$10,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'SAP',
    variants: ['SAP SE'],
    industry: 'Technology',
    domain: 'sap.com',
    bonus_amount: '$2,000-$7,500',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'ServiceNow',
    industry: 'Technology',
    domain: 'servicenow.com',
    bonus_amount: '$3,000-$10,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Snowflake',
    industry: 'Technology',
    domain: 'snowflake.com',
    bonus_amount: '$5,000-$15,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Databricks',
    industry: 'Technology',
    domain: 'databricks.com',
    bonus_amount: '$5,000-$15,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Palantir',
    variants: ['Palantir Technologies'],
    industry: 'Technology',
    domain: 'palantir.com',
    bonus_amount: '$3,000-$10,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Workday',
    industry: 'Technology',
    domain: 'workday.com',
    bonus_amount: '$2,500-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'VMware',
    industry: 'Technology',
    domain: 'vmware.com',
    bonus_amount: '$2,000-$7,500',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Cisco',
    variants: ['Cisco Systems'],
    industry: 'Technology',
    domain: 'cisco.com',
    bonus_amount: '$2,000-$7,500',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Dell Technologies',
    variants: ['Dell', 'Dell Inc.'],
    industry: 'Technology',
    domain: 'dell.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'HP',
    variants: ['Hewlett-Packard', 'HP Inc.'],
    industry: 'Technology',
    domain: 'hp.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Palo Alto Networks',
    industry: 'Technology',
    domain: 'paloaltonetworks.com',
    bonus_amount: '$3,000-$12,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'CrowdStrike',
    industry: 'Technology',
    domain: 'crowdstrike.com',
    bonus_amount: '$3,000-$10,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Okta',
    industry: 'Technology',
    domain: 'okta.com',
    bonus_amount: '$2,500-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Twilio',
    industry: 'Technology',
    domain: 'twilio.com',
    bonus_amount: '$2,500-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Zendesk',
    industry: 'Technology',
    domain: 'zendesk.com',
    bonus_amount: '$2,000-$7,500',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'HubSpot',
    industry: 'Technology',
    domain: 'hubspot.com',
    bonus_amount: '$2,500-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Atlassian',
    industry: 'Technology',
    domain: 'atlassian.com',
    bonus_amount: '$3,000-$10,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Dropbox',
    industry: 'Technology',
    domain: 'dropbox.com',
    bonus_amount: '$2,000-$7,500',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Box',
    variants: ['Box Inc.'],
    industry: 'Technology',
    domain: 'box.com',
    bonus_amount: '$2,000-$7,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'DocuSign',
    industry: 'Technology',
    domain: 'docusign.com',
    bonus_amount: '$2,000-$7,500',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Zoom',
    variants: ['Zoom Video Communications'],
    industry: 'Technology',
    domain: 'zoom.us',
    bonus_amount: '$2,000-$7,500',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Slack',
    industry: 'Technology',
    domain: 'slack.com',
    bonus_amount: '$2,500-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Intuit',
    industry: 'Technology',
    domain: 'intuit.com',
    bonus_amount: '$2,000-$7,500',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Autodesk',
    industry: 'Technology',
    domain: 'autodesk.com',
    bonus_amount: '$2,000-$6,500',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Roblox',
    industry: 'Technology',
    domain: 'roblox.com',
    bonus_amount: '$3,000-$10,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'DoorDash',
    industry: 'Technology',
    domain: 'doordash.com',
    bonus_amount: '$2,000-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Instacart',
    variants: ['Maplebear Inc.'],
    industry: 'Technology',
    domain: 'instacart.com',
    bonus_amount: '$2,000-$7,500',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Rivian',
    industry: 'Automotive',
    domain: 'rivian.com',
    bonus_amount: '$2,500-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Tesla',
    variants: ['Tesla Inc.', 'Tesla Motors'],
    industry: 'Automotive',
    domain: 'tesla.com',
    bonus_amount: '$5,000-$10,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'SpaceX',
    variants: ['Space Exploration Technologies'],
    industry: 'Aerospace',
    domain: 'spacex.com',
    bonus_amount: '$2,500-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Moderna',
    industry: 'Biotechnology',
    domain: 'modernatx.com',
    bonus_amount: 'Variable',
    confidence: 'low',
    data_source: 'Glassdoor',
  },

  // ─── Financial Services ──────────────────────────────────────────────────────

  {
    name: 'JPMorgan Chase',
    variants: ['JP Morgan', 'Chase', 'JPMorgan'],
    industry: 'Financial Services',
    domain: 'jpmorganchase.com',
    bonus_amount: '$2,000-$10,000',
    bonus_mid: '$5,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'Goldman Sachs',
    variants: ['Goldman Sachs Group'],
    industry: 'Financial Services',
    domain: 'goldmansachs.com',
    bonus_amount: 'Variable',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Morgan Stanley',
    industry: 'Financial Services',
    domain: 'morganstanley.com',
    bonus_amount: '$2,500-$10,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Citigroup',
    variants: ['Citi', 'Citibank'],
    industry: 'Financial Services',
    domain: 'citigroup.com',
    bonus_amount: '$2,000-$7,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Bank of America',
    variants: ['BofA', 'Bank of America Merrill Lynch'],
    industry: 'Financial Services',
    domain: 'bankofamerica.com',
    bonus_amount: '$1,500-$6,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Wells Fargo',
    variants: ['Wells Fargo Bank'],
    industry: 'Financial Services',
    domain: 'wellsfargo.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Capital One',
    industry: 'Financial Services',
    domain: 'capitalone.com',
    bonus_amount: '$2,000-$7,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'SoFi',
    variants: ['SoFi Technologies'],
    industry: 'Financial Services',
    domain: 'sofi.com',
    bonus_amount: '$50-$500',
    notes: 'Paid $54M+ total in referral bonuses (customer referral program)',
    confidence: 'high',
    data_source: 'company announcement',
  },
  {
    name: 'Fidelity Investments',
    variants: ['Fidelity'],
    industry: 'Financial Services',
    domain: 'fidelity.com',
    bonus_amount: '$2,000-$7,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Charles Schwab',
    variants: ['Schwab'],
    industry: 'Financial Services',
    domain: 'schwab.com',
    bonus_amount: '$2,000-$7,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'BlackRock',
    industry: 'Financial Services',
    domain: 'blackrock.com',
    bonus_amount: '$3,000-$10,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Vanguard',
    industry: 'Financial Services',
    domain: 'vanguard.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'American Express',
    variants: ['Amex'],
    industry: 'Financial Services',
    domain: 'americanexpress.com',
    bonus_amount: '$2,000-$7,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Visa',
    variants: ['Visa Inc.'],
    industry: 'Financial Services',
    domain: 'visa.com',
    bonus_amount: '$2,500-$8,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Mastercard',
    industry: 'Financial Services',
    domain: 'mastercard.com',
    bonus_amount: '$2,500-$8,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'PayPal',
    variants: ['PayPal Holdings'],
    industry: 'Financial Services',
    domain: 'paypal.com',
    bonus_amount: '$2,000-$7,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'US Bank',
    variants: ['U.S. Bank', 'U.S. Bancorp'],
    industry: 'Financial Services',
    domain: 'usbank.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'TD Bank',
    variants: ['Toronto-Dominion Bank'],
    industry: 'Financial Services',
    domain: 'td.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'PNC Financial',
    variants: ['PNC', 'PNC Bank'],
    industry: 'Financial Services',
    domain: 'pnc.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Ally Financial',
    variants: ['Ally Bank'],
    industry: 'Financial Services',
    domain: 'ally.com',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Discover Financial',
    variants: ['Discover', 'Discover Bank'],
    industry: 'Financial Services',
    domain: 'discover.com',
    bonus_amount: '$1,500-$5,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },

  // ─── Consulting ──────────────────────────────────────────────────────────────

  {
    name: 'Deloitte',
    variants: ['Deloitte Consulting', 'Deloitte & Touche'],
    industry: 'Consulting',
    domain: 'deloitte.com',
    bonus_amount: '$4,000-$16,000',
    bonus_entry: '$4,000',
    bonus_mid: '$8,000',
    bonus_senior: '$16,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'PwC',
    variants: ['PricewaterhouseCoopers'],
    industry: 'Consulting',
    domain: 'pwc.com',
    bonus_amount: '$300-$1,500+',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'EY',
    variants: ['Ernst & Young'],
    industry: 'Consulting',
    domain: 'ey.com',
    bonus_amount: '$4,000-$15,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'KPMG',
    industry: 'Consulting',
    domain: 'kpmg.com',
    bonus_amount: '$4,000-$15,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'McKinsey',
    variants: ['McKinsey & Company'],
    industry: 'Consulting',
    domain: 'mckinsey.com',
    bonus_amount: '$5,000-$20,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'BCG',
    variants: ['Boston Consulting Group'],
    industry: 'Consulting',
    domain: 'bcg.com',
    bonus_amount: '$5,000-$20,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Bain',
    variants: ['Bain & Company'],
    industry: 'Consulting',
    domain: 'bain.com',
    bonus_amount: '$5,000-$20,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Accenture',
    variants: ['Accenture PLC'],
    industry: 'Consulting',
    domain: 'accenture.com',
    bonus_amount: '$2,000-$7,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Booz Allen Hamilton',
    variants: ['Booz Allen'],
    industry: 'Consulting',
    domain: 'boozallen.com',
    bonus_amount: '$2,500-$8,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Leidos',
    industry: 'Consulting',
    domain: 'leidos.com',
    bonus_amount: '$2,000-$7,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'SAIC',
    variants: ['Science Applications International Corporation'],
    industry: 'Consulting',
    domain: 'saic.com',
    bonus_amount: '$2,000-$7,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },

  // ─── Aerospace & Defense ─────────────────────────────────────────────────────

  {
    name: 'Boeing',
    variants: ['The Boeing Company'],
    industry: 'Aerospace',
    domain: 'boeing.com',
    bonus_amount: '$3,000-$10,000',
    notes: 'Up to $10,000 in Puget Sound region',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'Northrop Grumman',
    variants: ['Northrop Grumman Corporation'],
    industry: 'Aerospace',
    domain: 'northropgrumman.com',
    bonus_amount: 'Variable',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Raytheon',
    variants: ['Raytheon Technologies', 'RTX'],
    industry: 'Aerospace',
    domain: 'rtx.com',
    bonus_amount: '$2,000-$5,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'Lockheed Martin',
    variants: ['LMT'],
    industry: 'Aerospace',
    domain: 'lockheedmartin.com',
    bonus_amount: '$3,000-$5,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'General Dynamics',
    industry: 'Aerospace',
    domain: 'gd.com',
    bonus_amount: '$2,000-$7,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'L3Harris Technologies',
    variants: ['L3Harris', 'Harris Corporation'],
    industry: 'Aerospace',
    domain: 'l3harris.com',
    bonus_amount: '$2,000-$6,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'BAE Systems',
    industry: 'Aerospace',
    domain: 'baesystems.com',
    bonus_amount: '$1,500-$5,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },

  // ─── Healthcare & Pharma ─────────────────────────────────────────────────────

  {
    name: 'UnitedHealth Group',
    variants: ['UHG', 'United Healthcare', 'Optum'],
    industry: 'Healthcare',
    domain: 'unitedhealthgroup.com',
    bonus_amount: 'Up to $5,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'Rush University Medical Center',
    variants: ['Rush Medical Center', 'Rush System'],
    industry: 'Healthcare',
    domain: 'rush.edu',
    bonus_amount: '$1,500-$10,000',
    notes: '$10,000 for nurse referrals',
    special_programs: { nursing_referral: '$10,000' },
    confidence: 'high',
    data_source: 'company announcement',
  },
  {
    name: 'Albany Medical Center',
    variants: ['Albany Med'],
    industry: 'Healthcare',
    domain: 'amc.edu',
    bonus_amount: '$500-$2,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'AMN Healthcare',
    industry: 'Healthcare',
    domain: 'amnhealthcare.com',
    bonus_amount: '$500-$5,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'Pfizer',
    variants: ['Pfizer Inc.'],
    industry: 'Pharmaceuticals',
    domain: 'pfizer.com',
    bonus_amount: '$2,000-$7,500',
    payout_structure: '50% at 90 days, 50% at 180 days',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'Merck',
    variants: ['Merck & Co.', 'MSD'],
    industry: 'Pharmaceuticals',
    domain: 'merck.com',
    bonus_amount: '$2,000-$5,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'Johnson & Johnson',
    variants: ['J&J', 'Janssen'],
    industry: 'Pharmaceuticals',
    domain: 'jnj.com',
    bonus_amount: '$2,000-$5,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'CVS Health',
    variants: ['CVS Pharmacy', 'CVS Caremark', 'Aetna'],
    industry: 'Healthcare',
    domain: 'cvshealth.com',
    bonus_amount: '$1,500-$4,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Anthem',
    variants: ['Elevance Health'],
    industry: 'Healthcare',
    domain: 'antheminc.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Cigna',
    variants: ['Cigna Group'],
    industry: 'Healthcare',
    domain: 'cigna.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'HCA Healthcare',
    variants: ['HCA'],
    industry: 'Healthcare',
    domain: 'hcahealthcare.com',
    bonus_amount: '$1,500-$4,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Kaiser Permanente',
    industry: 'Healthcare',
    domain: 'kaiserpermanente.org',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Humana',
    industry: 'Healthcare',
    domain: 'humana.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'AbbVie',
    industry: 'Pharmaceuticals',
    domain: 'abbvie.com',
    bonus_amount: '$2,000-$7,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Bristol Myers Squibb',
    variants: ['BMS'],
    industry: 'Pharmaceuticals',
    domain: 'bms.com',
    bonus_amount: '$2,000-$6,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Eli Lilly',
    variants: ['Lilly'],
    industry: 'Pharmaceuticals',
    domain: 'lilly.com',
    bonus_amount: '$2,000-$7,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Abbott Laboratories',
    variants: ['Abbott'],
    industry: 'Healthcare',
    domain: 'abbott.com',
    bonus_amount: '$1,500-$6,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Medtronic',
    industry: 'Healthcare',
    domain: 'medtronic.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Boston Scientific',
    industry: 'Healthcare',
    domain: 'bostonscientific.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Stryker',
    industry: 'Healthcare',
    domain: 'stryker.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Baxter International',
    variants: ['Baxter'],
    industry: 'Healthcare',
    domain: 'baxter.com',
    bonus_amount: '$1,500-$4,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Becton Dickinson',
    variants: ['BD'],
    industry: 'Healthcare',
    domain: 'bd.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Danaher',
    industry: 'Healthcare',
    domain: 'danaher.com',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Thermo Fisher Scientific',
    variants: ['Thermo Fisher'],
    industry: 'Healthcare',
    domain: 'thermofisher.com',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Agilent Technologies',
    variants: ['Agilent'],
    industry: 'Healthcare',
    domain: 'agilent.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Illumina',
    industry: 'Biotechnology',
    domain: 'illumina.com',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Regeneron Pharmaceuticals',
    variants: ['Regeneron'],
    industry: 'Biotechnology',
    domain: 'regeneron.com',
    bonus_amount: '$2,000-$7,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Gilead Sciences',
    variants: ['Gilead'],
    industry: 'Biotechnology',
    domain: 'gilead.com',
    bonus_amount: '$2,000-$7,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Biogen',
    industry: 'Biotechnology',
    domain: 'biogen.com',
    bonus_amount: '$2,000-$6,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Vertex Pharmaceuticals',
    variants: ['Vertex'],
    industry: 'Biotechnology',
    domain: 'vrtx.com',
    bonus_amount: '$2,000-$7,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },

  // ─── Retail & Consumer ───────────────────────────────────────────────────────

  {
    name: 'Target',
    variants: ['Target Corporation'],
    industry: 'Retail',
    domain: 'target.com',
    bonus_amount: 'Up to $3,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'Starbucks',
    variants: ['Starbucks Corporation'],
    industry: 'Retail',
    domain: 'starbucks.com',
    bonus_amount: '$1,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'Chipotle',
    variants: ['Chipotle Mexican Grill'],
    industry: 'Retail',
    domain: 'chipotle.com',
    bonus_amount: '$200-$750',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'Walmart',
    variants: ['Walmart Inc.', 'Wal-Mart'],
    industry: 'Retail',
    domain: 'walmart.com',
    bonus_amount: '$500-$3,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Home Depot',
    variants: ['The Home Depot'],
    industry: 'Retail',
    domain: 'homedepot.com',
    bonus_amount: '$500-$2,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Nike',
    variants: ['Nike Inc.'],
    industry: 'Retail',
    domain: 'nike.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: "Lowe's",
    variants: ["Lowe's Companies"],
    industry: 'Retail',
    domain: 'lowes.com',
    bonus_amount: '$500-$2,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Costco',
    variants: ['Costco Wholesale'],
    industry: 'Retail',
    domain: 'costco.com',
    bonus_amount: '$500-$2,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Best Buy',
    variants: ['Best Buy Co.'],
    industry: 'Retail',
    domain: 'bestbuy.com',
    bonus_amount: '$500-$2,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: "McDonald's",
    variants: ["McDonald's Corporation"],
    industry: 'Retail',
    domain: 'mcdonalds.com',
    bonus_amount: '$200-$1,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },

  // ─── Telecom ─────────────────────────────────────────────────────────────────

  {
    name: 'T-Mobile',
    variants: ['T-Mobile US'],
    industry: 'Telecommunications',
    domain: 't-mobile.com',
    bonus_amount: '$1,000-$5,500',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'AT&T',
    industry: 'Telecommunications',
    domain: 'att.com',
    bonus_amount: '$1,000-$4,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Verizon',
    variants: ['Verizon Communications'],
    industry: 'Telecommunications',
    domain: 'verizon.com',
    bonus_amount: '$1,000-$4,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Comcast',
    variants: ['Comcast Corporation', 'Xfinity'],
    industry: 'Telecommunications',
    domain: 'comcast.com',
    bonus_amount: '$1,000-$4,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Charter Communications',
    variants: ['Spectrum'],
    industry: 'Telecommunications',
    domain: 'spectrum.com',
    bonus_amount: '$1,000-$3,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Dish Network',
    variants: ['DISH', 'EchoStar'],
    industry: 'Telecommunications',
    domain: 'dish.com',
    bonus_amount: '$500-$2,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },

  // ─── Construction & Engineering ──────────────────────────────────────────────

  {
    name: 'Turner Construction',
    variants: ['Turner Construction Company'],
    industry: 'Construction',
    domain: 'turnerconstruction.com',
    bonus_amount: '$1,500-$3,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'Hydro Extrusions',
    variants: ['Hydro', 'Norsk Hydro'],
    industry: 'Manufacturing',
    domain: 'hydro.com',
    bonus_amount: '$3,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'Bechtel',
    industry: 'Engineering',
    domain: 'bechtel.com',
    bonus_amount: '$2,000-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Fluor Corporation',
    variants: ['Fluor'],
    industry: 'Engineering',
    domain: 'fluor.com',
    bonus_amount: '$2,000-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Jacobs Engineering',
    variants: ['Jacobs'],
    industry: 'Engineering',
    domain: 'jacobs.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'AECOM',
    industry: 'Engineering',
    domain: 'aecom.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'KBR',
    variants: ['KBR Inc.'],
    industry: 'Engineering',
    domain: 'kbr.com',
    bonus_amount: '$2,000-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },

  // ─── Food & Beverage ─────────────────────────────────────────────────────────

  {
    name: 'Coca-Cola Consolidated',
    variants: ['COKE', 'Coke Consolidated'],
    industry: 'Food & Beverage',
    domain: 'cokeconsolidated.com',
    bonus_amount: '$1,000-$5,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'PepsiCo',
    variants: ['Pepsi'],
    industry: 'Food & Beverage',
    domain: 'pepsico.com',
    bonus_amount: '$3,000-$6,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'Kraft Heinz',
    variants: ['Kraft', 'Heinz'],
    industry: 'Food & Beverage',
    domain: 'kraftheinzcompany.com',
    bonus_amount: '$1,500-$4,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Procter & Gamble',
    variants: ['P&G'],
    industry: 'Consumer Goods',
    domain: 'pg.com',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Unilever',
    variants: ['Unilever PLC'],
    industry: 'Consumer Goods',
    domain: 'unilever.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Colgate-Palmolive',
    variants: ['Colgate'],
    industry: 'Consumer Goods',
    domain: 'colgatepalmolive.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: "Kellogg's",
    variants: ['Kellogg Company', 'WK Kellogg'],
    industry: 'Food & Beverage',
    domain: 'kelloggs.com',
    bonus_amount: '$1,500-$4,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'General Mills',
    industry: 'Food & Beverage',
    domain: 'generalmills.com',
    bonus_amount: '$1,500-$4,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Conagra Brands',
    variants: ['ConAgra'],
    industry: 'Food & Beverage',
    domain: 'conagrabrands.com',
    bonus_amount: '$1,500-$4,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },

  // ─── Hospitality ─────────────────────────────────────────────────────────────

  {
    name: 'Hyatt Hotels',
    variants: ['Hyatt', 'Grand Hyatt', 'Park Hyatt'],
    industry: 'Hospitality',
    domain: 'hyatt.com',
    bonus_amount: '$1,000-$3,000',
    confidence: 'high',
    data_source: 'Glassdoor',
  },
  {
    name: 'Marriott International',
    variants: ['Marriott', 'Sheraton', 'Westin', 'W Hotels'],
    industry: 'Hospitality',
    domain: 'marriott.com',
    bonus_amount: '$1,000-$3,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Hilton',
    variants: ['Hilton Hotels', 'Hilton Worldwide'],
    industry: 'Hospitality',
    domain: 'hilton.com',
    bonus_amount: '$1,000-$3,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'IHG',
    variants: ['InterContinental Hotels Group', 'Holiday Inn', 'Crowne Plaza'],
    industry: 'Hospitality',
    domain: 'ihg.com',
    bonus_amount: '$500-$2,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Wyndham Hotels & Resorts',
    variants: ['Wyndham'],
    industry: 'Hospitality',
    domain: 'wyndhamhotels.com',
    bonus_amount: '$500-$2,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },

  // ─── Industrial & Energy ─────────────────────────────────────────────────────

  {
    name: 'General Electric',
    variants: ['GE', 'GE Vernova', 'GE Aerospace'],
    industry: 'Industrial',
    domain: 'ge.com',
    bonus_amount: '$1,500-$5,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Honeywell',
    variants: ['Honeywell International'],
    industry: 'Industrial',
    domain: 'honeywell.com',
    bonus_amount: '$1,500-$5,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: '3M',
    variants: ['Minnesota Mining and Manufacturing', 'MMM'],
    industry: 'Industrial',
    domain: '3m.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Caterpillar',
    variants: ['CAT'],
    industry: 'Industrial',
    domain: 'cat.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Deere & Company',
    variants: ['John Deere'],
    industry: 'Industrial',
    domain: 'deere.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Eaton',
    variants: ['Eaton Corporation'],
    industry: 'Industrial',
    domain: 'eaton.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Emerson Electric',
    variants: ['Emerson'],
    industry: 'Industrial',
    domain: 'emerson.com',
    bonus_amount: '$1,500-$4,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Parker Hannifin',
    variants: ['Parker'],
    industry: 'Industrial',
    domain: 'parker.com',
    bonus_amount: '$1,500-$4,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Rockwell Automation',
    variants: ['Rockwell'],
    industry: 'Industrial',
    domain: 'rockwellautomation.com',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Exxon Mobil',
    variants: ['ExxonMobil', 'Exxon'],
    industry: 'Energy',
    domain: 'exxonmobil.com',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Chevron',
    variants: ['Chevron Corporation'],
    industry: 'Energy',
    domain: 'chevron.com',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'ConocoPhillips',
    variants: ['ConocoPhillips Company'],
    industry: 'Energy',
    domain: 'conocophillips.com',
    bonus_amount: '$2,000-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Halliburton',
    industry: 'Energy',
    domain: 'halliburton.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Schlumberger',
    variants: ['SLB'],
    industry: 'Energy',
    domain: 'slb.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Baker Hughes',
    industry: 'Energy',
    domain: 'bakerhughes.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'NextEra Energy',
    variants: ['FPL', 'Florida Power & Light'],
    industry: 'Energy',
    domain: 'nexteraenergy.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Duke Energy',
    industry: 'Energy',
    domain: 'duke-energy.com',
    bonus_amount: '$1,500-$4,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },

  // ─── Logistics & Transportation ──────────────────────────────────────────────

  {
    name: 'FedEx',
    variants: ['FedEx Corporation', 'Federal Express'],
    industry: 'Logistics',
    domain: 'fedex.com',
    bonus_amount: '$1,000-$3,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'UPS',
    variants: ['United Parcel Service'],
    industry: 'Logistics',
    domain: 'ups.com',
    bonus_amount: '$1,000-$3,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'XPO Logistics',
    variants: ['XPO'],
    industry: 'Logistics',
    domain: 'xpo.com',
    bonus_amount: '$1,000-$3,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'J.B. Hunt',
    variants: ['JB Hunt Transport'],
    industry: 'Logistics',
    domain: 'jbhunt.com',
    bonus_amount: '$1,000-$3,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Werner Enterprises',
    variants: ['Werner'],
    industry: 'Logistics',
    domain: 'werner.com',
    bonus_amount: '$500-$2,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },

  // ─── Media & Entertainment ───────────────────────────────────────────────────

  {
    name: 'Walt Disney',
    variants: ['Disney', 'The Walt Disney Company'],
    industry: 'Media',
    domain: 'disney.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Warner Bros. Discovery',
    variants: ['Warner Bros', 'HBO', 'CNN'],
    industry: 'Media',
    domain: 'wbd.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'NBCUniversal',
    variants: ['NBC', 'Universal Pictures', 'Peacock'],
    industry: 'Media',
    domain: 'nbcuniversal.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Paramount Global',
    variants: ['Paramount', 'CBS', 'MTV'],
    industry: 'Media',
    domain: 'paramount.com',
    bonus_amount: '$1,000-$4,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Fox Corporation',
    variants: ['Fox', 'Fox News'],
    industry: 'Media',
    domain: 'foxcorporation.com',
    bonus_amount: '$1,000-$4,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Spotify',
    industry: 'Media',
    domain: 'spotify.com',
    bonus_amount: '$2,000-$7,500',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Epic Games',
    industry: 'Gaming',
    domain: 'epicgames.com',
    bonus_amount: '$2,000-$8,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Activision Blizzard',
    variants: ['Activision', 'Blizzard Entertainment', 'King'],
    industry: 'Gaming',
    domain: 'activisionblizzard.com',
    bonus_amount: '$2,000-$7,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Electronic Arts',
    variants: ['EA', 'EA Sports'],
    industry: 'Gaming',
    domain: 'ea.com',
    bonus_amount: '$2,000-$7,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Take-Two Interactive',
    variants: ['Rockstar Games', '2K Games'],
    industry: 'Gaming',
    domain: 'take2games.com',
    bonus_amount: '$2,000-$7,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },

  // ─── Insurance ───────────────────────────────────────────────────────────────

  {
    name: 'Allstate',
    variants: ['Allstate Corporation'],
    industry: 'Insurance',
    domain: 'allstate.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'State Farm',
    industry: 'Insurance',
    domain: 'statefarm.com',
    bonus_amount: '$1,000-$4,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Progressive',
    variants: ['Progressive Corporation'],
    industry: 'Insurance',
    domain: 'progressive.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Travelers',
    variants: ['Travelers Companies'],
    industry: 'Insurance',
    domain: 'travelers.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'MetLife',
    variants: ['MetLife Inc.'],
    industry: 'Insurance',
    domain: 'metlife.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Prudential Financial',
    variants: ['Prudential'],
    industry: 'Insurance',
    domain: 'prudential.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Lincoln National',
    variants: ['Lincoln Financial Group'],
    industry: 'Insurance',
    domain: 'lfg.com',
    bonus_amount: '$1,500-$4,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Unum Group',
    variants: ['Unum'],
    industry: 'Insurance',
    domain: 'unum.com',
    bonus_amount: '$1,000-$4,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },

  // ─── Real Estate ─────────────────────────────────────────────────────────────

  {
    name: 'CBRE',
    variants: ['CBRE Group', 'CB Richard Ellis'],
    industry: 'Real Estate',
    domain: 'cbre.com',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'JLL',
    variants: ['Jones Lang LaSalle'],
    industry: 'Real Estate',
    domain: 'jll.com',
    bonus_amount: '$2,000-$5,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Prologis',
    industry: 'Real Estate',
    domain: 'prologis.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Zillow',
    variants: ['Zillow Group'],
    industry: 'Real Estate',
    domain: 'zillow.com',
    bonus_amount: '$2,000-$7,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },

  // ─── Staffing & HR ───────────────────────────────────────────────────────────

  {
    name: 'Adecco',
    variants: ['Adecco Group'],
    industry: 'Staffing',
    domain: 'adecco.com',
    bonus_amount: '$500-$2,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'ManpowerGroup',
    variants: ['Manpower'],
    industry: 'Staffing',
    domain: 'manpowergroup.com',
    bonus_amount: '$500-$2,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Robert Half',
    industry: 'Staffing',
    domain: 'roberthalf.com',
    bonus_amount: '$500-$2,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Korn Ferry',
    industry: 'Staffing',
    domain: 'kornferry.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },

  // ─── Education ───────────────────────────────────────────────────────────────

  {
    name: 'Chegg',
    industry: 'Education',
    domain: 'chegg.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Coursera',
    industry: 'Education',
    domain: 'coursera.org',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Duolingo',
    industry: 'Education',
    domain: 'duolingo.com',
    bonus_amount: '$2,000-$7,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },

  // ─── Global IT Services ──────────────────────────────────────────────────────

  {
    name: 'Cognizant',
    variants: ['Cognizant Technology Solutions'],
    industry: 'Technology',
    domain: 'cognizant.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Infosys',
    industry: 'Technology',
    domain: 'infosys.com',
    bonus_amount: '$1,000-$3,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Wipro',
    industry: 'Technology',
    domain: 'wipro.com',
    bonus_amount: '$1,000-$3,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Tata Consultancy Services',
    variants: ['TCS'],
    industry: 'Technology',
    domain: 'tcs.com',
    bonus_amount: '$1,000-$3,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'HCL Technologies',
    variants: ['HCL'],
    industry: 'Technology',
    domain: 'hcltech.com',
    bonus_amount: '$1,000-$3,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Capgemini',
    industry: 'Technology',
    domain: 'capgemini.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'CGI',
    variants: ['CGI Group'],
    industry: 'Technology',
    domain: 'cgi.com',
    bonus_amount: '$1,500-$4,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Peraton',
    industry: 'Technology',
    domain: 'peraton.com',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'ManTech',
    variants: ['ManTech International'],
    industry: 'Technology',
    domain: 'mantech.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'MITRE',
    variants: ['MITRE Corporation'],
    industry: 'Research',
    domain: 'mitre.org',
    bonus_amount: '$2,000-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Gartner',
    industry: 'Technology',
    domain: 'gartner.com',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Fiserv',
    industry: 'Technology',
    domain: 'fiserv.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Broadridge Financial',
    variants: ['Broadridge'],
    industry: 'Technology',
    domain: 'broadridge.com',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },

  // ─── Semiconductors ──────────────────────────────────────────────────────────

  {
    name: 'Lam Research',
    industry: 'Technology',
    domain: 'lamresearch.com',
    bonus_amount: '$3,000-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Applied Materials',
    industry: 'Technology',
    domain: 'appliedmaterials.com',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'KLA Corporation',
    variants: ['KLA'],
    industry: 'Technology',
    domain: 'kla.com',
    bonus_amount: '$2,000-$5,500',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Marvell Technology',
    variants: ['Marvell'],
    industry: 'Technology',
    domain: 'marvell.com',
    bonus_amount: '$3,000-$7,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Broadcom',
    variants: ['Broadcom Inc.'],
    industry: 'Technology',
    domain: 'broadcom.com',
    bonus_amount: '$3,000-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Texas Instruments',
    variants: ['TI'],
    industry: 'Technology',
    domain: 'ti.com',
    bonus_amount: '$2,000-$5,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Micron Technology',
    variants: ['Micron'],
    industry: 'Technology',
    domain: 'micron.com',
    bonus_amount: '$2,000-$5,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Western Digital',
    variants: ['WD', 'SanDisk'],
    industry: 'Technology',
    domain: 'westerndigital.com',
    bonus_amount: '$2,000-$5,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Seagate Technology',
    variants: ['Seagate'],
    industry: 'Technology',
    domain: 'seagate.com',
    bonus_amount: '$1,500-$4,500',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Juniper Networks',
    industry: 'Technology',
    domain: 'juniper.net',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'F5',
    variants: ['F5 Networks', 'F5 Inc.'],
    industry: 'Technology',
    domain: 'f5.com',
    bonus_amount: '$2,000-$5,500',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'NetApp',
    industry: 'Technology',
    domain: 'netapp.com',
    bonus_amount: '$2,000-$5,500',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Pure Storage',
    industry: 'Technology',
    domain: 'purestorage.com',
    bonus_amount: '$3,000-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },

  // ─── Cybersecurity ───────────────────────────────────────────────────────────

  {
    name: 'Fortinet',
    industry: 'Technology',
    domain: 'fortinet.com',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Check Point Software',
    variants: ['Check Point'],
    industry: 'Technology',
    domain: 'checkpoint.com',
    bonus_amount: '$2,000-$5,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'SentinelOne',
    industry: 'Technology',
    domain: 'sentinelone.com',
    bonus_amount: '$3,000-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Zscaler',
    industry: 'Technology',
    domain: 'zscaler.com',
    bonus_amount: '$2,500-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },

  // ─── SaaS / High-growth ──────────────────────────────────────────────────────

  {
    name: 'Veeva Systems',
    variants: ['Veeva'],
    industry: 'Technology',
    domain: 'veeva.com',
    bonus_amount: '$2,000-$7,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Toast',
    variants: ['Toast Inc.'],
    industry: 'Technology',
    domain: 'pos.toasttab.com',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Figma',
    industry: 'Technology',
    domain: 'figma.com',
    bonus_amount: '$5,000-$15,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Notion',
    industry: 'Technology',
    domain: 'notion.so',
    bonus_amount: '$3,000-$10,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Canva',
    industry: 'Technology',
    domain: 'canva.com',
    bonus_amount: '$2,000-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'GitHub',
    industry: 'Technology',
    domain: 'github.com',
    bonus_amount: '$2,500-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'HashiCorp',
    industry: 'Technology',
    domain: 'hashicorp.com',
    bonus_amount: '$3,000-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Elastic',
    variants: ['Elasticsearch'],
    industry: 'Technology',
    domain: 'elastic.co',
    bonus_amount: '$2,500-$7,500',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'MongoDB',
    industry: 'Technology',
    domain: 'mongodb.com',
    bonus_amount: '$3,000-$9,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Confluent',
    industry: 'Technology',
    domain: 'confluent.io',
    bonus_amount: '$3,000-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Datadog',
    industry: 'Technology',
    domain: 'datadoghq.com',
    bonus_amount: '$3,000-$9,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'New Relic',
    industry: 'Technology',
    domain: 'newrelic.com',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'PagerDuty',
    industry: 'Technology',
    domain: 'pagerduty.com',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Amplitude',
    industry: 'Technology',
    domain: 'amplitude.com',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Brex',
    industry: 'Technology',
    domain: 'brex.com',
    bonus_amount: '$3,000-$9,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Plaid',
    industry: 'Technology',
    domain: 'plaid.com',
    bonus_amount: '$3,000-$9,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Chime',
    industry: 'Technology',
    domain: 'chime.com',
    bonus_amount: '$3,000-$8,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Affirm',
    industry: 'Technology',
    domain: 'affirm.com',
    bonus_amount: '$2,500-$7,500',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Klarna',
    industry: 'Technology',
    domain: 'klarna.com',
    bonus_amount: '$2,000-$7,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },

  // ─── Autonomous Vehicles ─────────────────────────────────────────────────────

  {
    name: 'Waymo',
    industry: 'Technology',
    domain: 'waymo.com',
    bonus_amount: '$3,000-$10,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Cruise',
    variants: ['Cruise LLC', 'GM Cruise'],
    industry: 'Technology',
    domain: 'getcruise.com',
    bonus_amount: '$3,000-$9,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'Lucid Motors',
    variants: ['Lucid Group'],
    industry: 'Automotive',
    domain: 'lucidmotors.com',
    bonus_amount: '$2,000-$6,000',
    confidence: 'medium',
    data_source: 'levels.fyi',
  },
  {
    name: 'General Motors',
    variants: ['GM'],
    industry: 'Automotive',
    domain: 'gm.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Ford Motor Company',
    variants: ['Ford'],
    industry: 'Automotive',
    domain: 'ford.com',
    bonus_amount: '$1,500-$5,000',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
  {
    name: 'Stellantis',
    variants: ['Chrysler', 'Jeep', 'RAM', 'Dodge'],
    industry: 'Automotive',
    domain: 'stellantis.com',
    bonus_amount: '$1,500-$4,500',
    confidence: 'medium',
    data_source: 'Glassdoor',
  },
];

// ─── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Look up or create a company_directory row by normalized name.
 * Returns the company id on success, null on error.
 */
export async function lookupOrCreateCompany(
  name: string,
  industry?: string,
  domain?: string,
): Promise<string | null> {
  const nameNormalized = name.toLowerCase().trim();

  // Try exact lookup first
  const { data: existing, error: lookupError } = await supabaseAdmin
    .from('company_directory')
    .select('id')
    .eq('name_normalized', nameNormalized)
    .limit(1)
    .maybeSingle();

  if (lookupError) {
    logger.warn(
      { error: lookupError.message, name },
      'seed-referral-programs: lookup error',
    );
    return null;
  }

  if (existing) {
    return (existing as { id: string }).id;
  }

  // Create new entry
  const { data: created, error: insertError } = await supabaseAdmin
    .from('company_directory')
    .insert({
      name_normalized: nameNormalized,
      name_display: name,
      name_variants: [nameNormalized],
      ...(industry ? { industry } : {}),
      ...(domain ? { domain } : {}),
    })
    .select('id')
    .single();

  if (insertError) {
    // Race condition — another process inserted between our lookup and insert
    if (insertError.code === '23505') {
      const { data: raceExisting } = await supabaseAdmin
        .from('company_directory')
        .select('id')
        .eq('name_normalized', nameNormalized)
        .single();
      return (raceExisting as { id: string } | null)?.id ?? null;
    }
    logger.error(
      { error: insertError.message, name },
      'seed-referral-programs: insert company failed',
    );
    return null;
  }

  return (created as { id: string }).id;
}

// ─── Public API ────────────────────────────────────────────────────────────────

/**
 * Seed the referral_bonus_programs table with known companies.
 *
 * Idempotent — safe to run multiple times. Uses upsert on company_id so
 * re-runs update all bonus fields without creating duplicates.
 */
export async function seedReferralBonusPrograms(): Promise<void> {
  logger.info(
    { total: REFERRAL_COMPANIES.length },
    'seed-referral-programs: starting seed',
  );

  let companiesProcessed = 0;
  let companiesCreated = 0;
  let programsUpserted = 0;
  let errors = 0;

  for (const entry of REFERRAL_COMPANIES) {
    try {
      const companyId = await lookupOrCreateCompany(
        entry.name,
        entry.industry,
        entry.domain,
      );

      if (!companyId) {
        logger.warn(
          { name: entry.name },
          'seed-referral-programs: could not resolve company id, skipping',
        );
        errors++;
        companiesProcessed++;
        continue;
      }

      // Determine if this was a newly created company (no existing referral row)
      const { data: existingProgram } = await supabaseAdmin
        .from('referral_bonus_programs')
        .select('id')
        .eq('company_id', companyId)
        .limit(1)
        .maybeSingle();

      const isNew = !existingProgram;

      // Upsert the referral program row keyed on company_id
      const { error: upsertError } = await supabaseAdmin
        .from('referral_bonus_programs')
        .upsert(
          {
            company_id: companyId,
            bonus_amount: entry.bonus_amount,
            bonus_currency: 'USD',
            source: entry.data_source ?? 'industry_data',
            ...(entry.bonus_entry !== undefined ? { bonus_entry: entry.bonus_entry } : {}),
            ...(entry.bonus_mid !== undefined ? { bonus_mid: entry.bonus_mid } : {}),
            ...(entry.bonus_senior !== undefined ? { bonus_senior: entry.bonus_senior } : {}),
            ...(entry.bonus_executive !== undefined ? { bonus_executive: entry.bonus_executive } : {}),
            ...(entry.payout_structure !== undefined ? { payout_structure: entry.payout_structure } : {}),
            ...(entry.diversity_multiplier !== undefined ? { diversity_multiplier: entry.diversity_multiplier } : {}),
            ...(entry.special_programs !== undefined ? { special_programs: entry.special_programs } : {}),
            ...(entry.confidence !== undefined ? { confidence: entry.confidence } : {}),
            ...(entry.data_source !== undefined ? { data_source: entry.data_source } : {}),
            ...(entry.notes !== undefined ? { notes: entry.notes } : {}),
            ...(entry.program_url !== undefined ? { program_url: entry.program_url } : {}),
            last_verified_at: new Date().toISOString(),
          },
          { onConflict: 'company_id' },
        );

      if (upsertError) {
        logger.error(
          { error: upsertError.message, name: entry.name },
          'seed-referral-programs: upsert failed',
        );
        errors++;
      } else {
        programsUpserted++;
        if (isNew) companiesCreated++;
      }

      companiesProcessed++;
    } catch (err) {
      logger.error(
        {
          error: err instanceof Error ? err.message : String(err),
          name: entry.name,
        },
        'seed-referral-programs: unexpected error processing company',
      );
      errors++;
      companiesProcessed++;
    }
  }

  logger.info(
    {
      companiesProcessed,
      companiesCreated,
      programsUpserted,
      errors,
    },
    'seed-referral-programs: seed complete',
  );
}
